version: '3.9'
services:
  ui:
    container_name: "visualisation"
    build: 
      context: ./visualisation
    ports:
      - 80:80
    
  data-analyser:
    container_name: "data-analyzer"
    build: 
      context: ./data-analyzer
   